<?php

return [
    'administrator' => [
        'manage_event_type_associations',
        'manage_collective_associations',
        'edit_event',
        'read_event',
        'delete_event',
        'edit_events',
        'edit_others_events',
        'publish_events',
        'read_private_events',
        'delete_events',
        'delete_private_events',
        'delete_published_events',
        'delete_others_events',
        'edit_private_events',
        'edit_published_events',
        'edit_collective',
        'read_collective',
        'delete_collective',
        'edit_collectives',
        'edit_others_collectives',
        'publish_collectives',
        'read_private_collectives',
        'delete_collectives',
        'delete_private_collectives',
        'delete_published_collectives',
        'delete_others_collectives',
        'edit_private_collectives',
        'edit_published_collectives',
    ],
    'editor' => [
        // Editors can assign collective terms via taxonomy assign_terms = edit_posts,
        // but they cannot manage/create/delete terms.
        'edit_event',
        'read_event',
        'delete_event',
        'edit_events',
        'publish_events',
        'read_private_events',
        'edit_published_events',
        'edit_collective',
        'read_collective',
        'delete_collective',
        'edit_collectives',
        'publish_collectives',
        'read_private_collectives',
        'edit_published_collectives',
    ],
];
